// ━━━ MOCK DATA FOR DIGIT HUP ━━━

import type { ServiceCardProps } from "@/components/marketplace/service-card"
import type { ProductCardProps } from "@/components/marketplace/product-card"
import type { SellerCardProps } from "@/components/marketplace/seller-card"

// ━━━ SERVICES DATA ━━━
export const featuredServices: ServiceCardProps[] = [
  {
    id: "1",
    slug: "professional-logo-design",
    title: "Professional Logo Design for Your Brand",
    description: "I will create a modern, memorable logo that captures your brand identity perfectly",
    price: 2500,
    category: "Graphic Design",
    seller: {
      name: "Yacine M.",
      level: "pro",
      verified: true,
    },
    rating: 4.9,
    reviewCount: 128,
    deliveryDays: 2,
    revisions: 3,
  },
  {
    id: "2",
    slug: "social-media-design-pack",
    title: "Complete Social Media Design Pack",
    description: "Get stunning social media posts, stories, and cover designs for all platforms",
    price: 1800,
    category: "Social Media",
    seller: {
      name: "Sara B.",
      level: "rising",
      verified: true,
    },
    rating: 4.8,
    reviewCount: 89,
    deliveryDays: 3,
    revisions: 2,
  },
  {
    id: "3",
    slug: "arabic-copywriting-services",
    title: "Professional Arabic Copywriting",
    description: "Engaging Arabic content for websites, ads, and marketing materials",
    price: 3000,
    category: "Writing",
    seller: {
      name: "Amine T.",
      level: "elite",
      verified: true,
    },
    rating: 5.0,
    reviewCount: 256,
    deliveryDays: 2,
    revisions: 4,
  },
  {
    id: "4",
    slug: "wordpress-website-development",
    title: "Custom WordPress Website Development",
    description: "Professional WordPress site with responsive design and SEO optimization",
    price: 12000,
    category: "Web Dev",
    seller: {
      name: "Rania K.",
      level: "pro",
      verified: true,
    },
    rating: 4.9,
    reviewCount: 167,
    deliveryDays: 7,
    revisions: 3,
  },
  {
    id: "5",
    slug: "motion-graphics-intro",
    title: "Custom Motion Graphics Video Intro",
    description: "Eye-catching animated intro for your YouTube channel or business",
    price: 5500,
    category: "Video",
    seller: {
      name: "Bilal D.",
      level: "rising",
      verified: true,
    },
    rating: 4.7,
    reviewCount: 72,
    deliveryDays: 4,
    revisions: 2,
  },
  {
    id: "6",
    slug: "ui-ux-design-figma",
    title: "UI/UX Design in Figma",
    description: "Modern, user-friendly interface designs for web and mobile apps",
    price: 8000,
    category: "Design",
    seller: {
      name: "Nesrine A.",
      level: "pro",
      verified: true,
    },
    rating: 4.9,
    reviewCount: 143,
    deliveryDays: 5,
    revisions: 5,
  },
  {
    id: "7",
    slug: "arabic-voice-over",
    title: "Professional Arabic Voice-Over",
    description: "Clear, engaging Arabic voice-over for videos, ads, and presentations",
    price: 2200,
    category: "Audio",
    seller: {
      name: "Karim S.",
      level: "new",
      verified: true,
    },
    rating: 4.6,
    reviewCount: 34,
    deliveryDays: 2,
    revisions: 2,
  },
  {
    id: "8",
    slug: "seo-setup-optimization",
    title: "Complete SEO Setup & Optimization",
    description: "Boost your website ranking with professional on-page SEO setup",
    price: 4500,
    category: "Marketing",
    seller: {
      name: "Lylia M.",
      level: "rising",
      verified: true,
    },
    rating: 4.8,
    reviewCount: 91,
    deliveryDays: 3,
    revisions: 1,
  },
]

// ━━━ PRODUCTS DATA ━━━
export const featuredProducts: ProductCardProps[] = [
  {
    id: "1",
    slug: "freelance-starter-pack",
    title: "Freelance Starter Pack",
    description: "Everything you need to launch your freelance career in Algeria",
    price: 1500,
    type: "toolkit",
    creator: { name: "Digit Hup Team" },
    rating: 4.9,
    purchaseCount: 847,
    isInstantDownload: true,
    isBestSeller: true,
  },
  {
    id: "2",
    slug: "master-canva-for-clients",
    title: "Master Canva for Clients",
    description: "Learn to create professional designs that clients will love",
    price: 2200,
    type: "course",
    creator: { name: "Sara B." },
    rating: 4.8,
    purchaseCount: 1200,
    isInstantDownload: true,
    isBestSeller: false,
  },
  {
    id: "3",
    slug: "proposal-templates-bundle",
    title: "Proposal Templates Bundle",
    description: "15+ professional proposal templates for any freelance project",
    price: 900,
    type: "template",
    creator: { name: "Amine T." },
    rating: 4.7,
    purchaseCount: 560,
    isInstantDownload: true,
    isNew: true,
  },
  {
    id: "4",
    slug: "client-communication-guide",
    title: "Client Communication Guide",
    description: "Master the art of professional client communication",
    price: 600,
    type: "ebook",
    creator: { name: "Rania K." },
    rating: 4.6,
    purchaseCount: 320,
    isInstantDownload: true,
  },
  {
    id: "5",
    slug: "logo-design-masterclass",
    title: "Logo Design Masterclass",
    description: "From concept to delivery - complete logo design workflow",
    price: 3500,
    type: "course",
    creator: { name: "Yacine M." },
    rating: 4.9,
    purchaseCount: 450,
    isInstantDownload: true,
  },
  {
    id: "6",
    slug: "social-media-calendar-kit",
    title: "Social Media Calendar Kit",
    description: "Plan your content for the entire year with these templates",
    price: 750,
    type: "template",
    creator: { name: "Sara B." },
    rating: 4.5,
    purchaseCount: 680,
    isInstantDownload: true,
    isBestSeller: true,
  },
  {
    id: "7",
    slug: "web-dev-project-checklist",
    title: "Web Dev Project Checklist",
    description: "Never miss a step with this comprehensive development checklist",
    price: 1100,
    type: "toolkit",
    creator: { name: "Rania K." },
    rating: 4.8,
    purchaseCount: 290,
    isInstantDownload: true,
    isNew: true,
  },
  {
    id: "8",
    slug: "pricing-your-services-right",
    title: "Pricing Your Services Right",
    description: "Learn to price your freelance services for maximum profit",
    price: 500,
    type: "ebook",
    creator: { name: "Digit Hup Team" },
    rating: 4.7,
    purchaseCount: 415,
    isInstantDownload: true,
  },
]

// ━━━ SELLERS DATA ━━━
export const topSellers: SellerCardProps[] = [
  {
    username: "yacine-m",
    name: "Yacine M.",
    specialty: "Logo & Brand Design",
    level: "pro",
    verified: true,
    rating: 4.9,
    completedOrders: 234,
    topService: {
      title: "Professional Logo Design",
      price: 2500,
    },
  },
  {
    username: "sara-b",
    name: "Sara B.",
    specialty: "Social Media Design",
    level: "rising",
    verified: true,
    rating: 4.8,
    completedOrders: 156,
    topService: {
      title: "Social Media Pack",
      price: 1800,
    },
  },
  {
    username: "amine-t",
    name: "Amine T.",
    specialty: "Arabic Copywriting",
    level: "elite",
    verified: true,
    rating: 5.0,
    completedOrders: 412,
    topService: {
      title: "Arabic Copywriting",
      price: 3000,
    },
  },
  {
    username: "rania-k",
    name: "Rania K.",
    specialty: "Web Development",
    level: "pro",
    verified: true,
    rating: 4.9,
    completedOrders: 189,
    topService: {
      title: "WordPress Development",
      price: 12000,
    },
  },
  {
    username: "nesrine-a",
    name: "Nesrine A.",
    specialty: "UI/UX Design",
    level: "pro",
    verified: true,
    rating: 4.9,
    completedOrders: 178,
    topService: {
      title: "UI/UX Design in Figma",
      price: 8000,
    },
  },
]

// ━━━ CATEGORIES DATA ━━━
export const categories = [
  { slug: "graphic-design", label: "Graphic Design", count: 245, icon: "palette" },
  { slug: "web-development", label: "Web Development", count: 189, icon: "code" },
  { slug: "writing-content", label: "Writing & Content", count: 167, icon: "pen" },
  { slug: "social-media", label: "Social Media", count: 156, icon: "share" },
  { slug: "video-motion", label: "Video & Motion", count: 98, icon: "video" },
  { slug: "courses-learning", label: "Courses & Learning", count: 76, icon: "graduation" },
  { slug: "templates-tools", label: "Templates & Tools", count: 124, icon: "file" },
  { slug: "tech-it-support", label: "Tech & IT Support", count: 87, icon: "settings" },
]

// ━━━ TESTIMONIALS DATA ━━━
export const testimonials = [
  {
    id: "1",
    name: "Walid B.",
    role: "Seller",
    location: "Constantine",
    avatar: "W",
    rating: 5,
    quote: "Digit Hup changed my life. I went from struggling to find clients to having a steady income doing what I love. The platform makes it so easy to showcase my work and connect with buyers.",
  },
  {
    id: "2",
    name: "Amira S.",
    role: "Buyer",
    location: "Alger",
    avatar: "A",
    rating: 5,
    quote: "Finally, a platform I can trust! The sellers are verified, prices are fair in DZD, and the quality of work I've received has been exceptional. Highly recommend for any business owner.",
  },
  {
    id: "3",
    name: "Tarek M.",
    role: "Seller",
    location: "Oran",
    avatar: "T",
    rating: 5,
    quote: "The courses on Digit Hup helped me level up my skills, and now I'm earning more than ever. It's not just a marketplace - it's a community that helps you grow.",
  },
]

// ━━━ FAQ DATA ━━━
export const faqItems = [
  {
    question: "Is Digit Hup free to join?",
    answer: "Yes! Creating an account and browsing services is completely free. Sellers only pay a small commission when they make a sale, and buyers pay nothing extra beyond the service price.",
  },
  {
    question: "How does seller verification work?",
    answer: "Every seller goes through a review process before their profile goes live. We check their portfolio, verify their skills, and ensure they meet our quality standards. Verified sellers display a blue checkmark on their profile.",
  },
  {
    question: "What payment methods are accepted in Algeria?",
    answer: "We accept Visa and Mastercard for international payments. We're also working on integrating Edahabia and CIB for local Algerian payments - coming soon!",
  },
  {
    question: "Can I sell both services and digital products?",
    answer: "Absolutely! Once you're a verified seller, you can list both freelance services and digital products like courses, templates, and ebooks on the platform.",
  },
  {
    question: "How long does order delivery take?",
    answer: "Delivery time depends on the service and package you choose. Each listing clearly shows the expected delivery time, ranging from 24 hours to several days depending on the complexity.",
  },
  {
    question: "What happens if I'm unhappy with a delivery?",
    answer: "You can request revisions based on your package (most include 2-3 revisions). If issues persist, our support team will help mediate, and you may be eligible for a refund under our buyer protection policy.",
  },
  {
    question: "Can I communicate with the seller before ordering?",
    answer: "Yes! You can message any seller directly from their profile or service page to discuss your project requirements before placing an order.",
  },
  {
    question: "Is the platform available in Arabic and French?",
    answer: "Yes! Digit Hup fully supports Arabic (with RTL layout), French, and English. You can switch languages anytime from the language selector in the navigation.",
  },
]
